// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpE8WhjhdgI4RuXfX1RhVxeClIkGFgag8',
    appId: '1:460628686164:web:e36e83e5a838d69dd004c1',
    messagingSenderId: '460628686164',
    projectId: 'lostpaws-cmdf',
    authDomain: 'lostpaws-cmdf.firebaseapp.com',
    storageBucket: 'lostpaws-cmdf.appspot.com',
    measurementId: 'G-R4G5NTW2DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8t0ROnNYOj0xaP6utJGg8Muc3M3vChQ',
    appId: '1:460628686164:android:c7b45884352322a1d004c1',
    messagingSenderId: '460628686164',
    projectId: 'lostpaws-cmdf',
    storageBucket: 'lostpaws-cmdf.appspot.com',
  );
}
